/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_RIMInformationTransfer_H_
#define	_NGAP_RIMInformationTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_TargetRANNodeID;
struct NGAP_SourceRANNodeID;
struct NGAP_RIMInformation;
struct NGAP_ProtocolExtensionContainer_11905P291;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_RIMInformationTransfer */
typedef struct NGAP_RIMInformationTransfer {
	struct NGAP_TargetRANNodeID	*targetRANNodeID;
	struct NGAP_SourceRANNodeID	*sourceRANNodeID;
	struct NGAP_RIMInformation	*rIMInformation;
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_RIMInformationTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_RIMInformationTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_NGAP_RIMInformationTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_RIMInformationTransfer_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_RIMInformationTransfer_H_ */
#include <asn_internal.h>
