/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "NGAP_ProtocolIE-ContainerList.h"

