/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_CauseNas_H_
#define	_NGAP_CauseNas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_CauseNas {
	NGAP_CauseNas_normal_release	= 0,
	NGAP_CauseNas_authentication_failure	= 1,
	NGAP_CauseNas_deregister	= 2,
	NGAP_CauseNas_unspecified	= 3,
	/*
	 * Enumeration is extensible
	 */
	NGAP_CauseNas_uE_not_in_PLMN_serving_area	= 4
} e_NGAP_CauseNas;

/* NGAP_CauseNas */
typedef long	 NGAP_CauseNas_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_CauseNas_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_CauseNas;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_CauseNas_specs_1;
asn_struct_free_f NGAP_CauseNas_free;
asn_struct_print_f NGAP_CauseNas_print;
asn_constr_check_f NGAP_CauseNas_constraint;
per_type_decoder_f NGAP_CauseNas_decode_aper;
per_type_encoder_f NGAP_CauseNas_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_CauseNas_H_ */
#include <asn_internal.h>
