/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_AlternativeQoSParaSetNotifyIndex_H_
#define	_NGAP_AlternativeQoSParaSetNotifyIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NGAP_AlternativeQoSParaSetNotifyIndex */
typedef long	 NGAP_AlternativeQoSParaSetNotifyIndex_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_AlternativeQoSParaSetNotifyIndex_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_AlternativeQoSParaSetNotifyIndex;
asn_struct_free_f NGAP_AlternativeQoSParaSetNotifyIndex_free;
asn_struct_print_f NGAP_AlternativeQoSParaSetNotifyIndex_print;
asn_constr_check_f NGAP_AlternativeQoSParaSetNotifyIndex_constraint;
per_type_decoder_f NGAP_AlternativeQoSParaSetNotifyIndex_decode_aper;
per_type_encoder_f NGAP_AlternativeQoSParaSetNotifyIndex_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_AlternativeQoSParaSetNotifyIndex_H_ */
#include <asn_internal.h>
