/*
 * Generated by asn1c-aecc039e-2026-05-01 (https://github.com/acetcom/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "../support/ngap-r19.2.0/38413-j20.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_ProtocolIE_ContainerList_H_
#define	_NGAP_ProtocolIE_ContainerList_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ProtocolIE_ContainerList_H_ */
#include <asn_internal.h>
