/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#ifndef	_NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer_H_
#define	_NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_Cell_CAGInformation;
struct NGAP_ProtocolExtensionContainer_11905P326;
struct NGAP_ProtocolExtensionContainer;

/* NGAP_TargetNGRANNode-ToSourceNGRANNode-FailureTransparentContainer */
typedef struct NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer {
	struct NGAP_Cell_CAGInformation	*cell_CAGInformation;	/* OPTIONAL */
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_TargetNGRANNode_ToSourceNGRANNode_FailureTransparentContainer_H_ */
#include <asn_internal.h>
