/*
 * Generated by asn1c-v1.4-25-g5b17cd0c-2026-04-20 (https://github.com/mouse07410/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../support/ngap-r17.3.0/38413-h30.asn"
 * 	`asn1c -pdu=all -fprefix=NGAP_ -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-CBOR -no-gen-OER -no-gen-UPER`
 */

#include "NGAP_CoverageEnhancementLevel.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_NGAP_CoverageEnhancementLevel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_CoverageEnhancementLevel = {
	"CoverageEnhancementLevel",
	"CoverageEnhancementLevel",
	&asn_OP_OCTET_STRING,
	asn_DEF_NGAP_CoverageEnhancementLevel_tags_1,
	sizeof(asn_DEF_NGAP_CoverageEnhancementLevel_tags_1)
		/sizeof(asn_DEF_NGAP_CoverageEnhancementLevel_tags_1[0]), /* 1 */
	asn_DEF_NGAP_CoverageEnhancementLevel_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_CoverageEnhancementLevel_tags_1)
		/sizeof(asn_DEF_NGAP_CoverageEnhancementLevel_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OCTET_STRING_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};

